spring.datasource.url=jdbc:postgresql://localhost:5432/company2
spring.datasource.username=postgres
spring.datasource.password=Nitin123


#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
